### ISSUE TITLE
Create release 1.6

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2749]
In preparation of the 1.6 release
Current estimate date to start this off - around 26 March.

- [x] Create 1.x branch
- [x] Update master to 1.(x+1)-SNAPSHOT
- [x] Update branch from 1.x-SNAPSHOT to 1.x
- [x] Remove release notes from branch
- [x] Verify notebooks
- [x] check UI
- [x] Run CTS ( #2850 ) 
- [x] Run FVTs (*SKIPPED* - see #426)
- [x] Check samples (*SKIPPED* - see #426)
- [x] Check swagger doc
- [x] Ensure release is current in master release notes & Add any final text
- [x] #2879 Launch release pipeline 
- [x] Verify docker image/charts/compose
- [x] Approve release
- [x] Verify artifacts on maven central
- [x] Create GitHub release
- [ ] Blog Post
- [x] Update master with new Type patchfile  (deferred to #2892)

**Comment by planetf1** [comment]
Agreed in team call 24 Mar to add info on:
 * Deprecations
 * Dependency updates
 * Significant bug fixes (tagged as user-reported and/or a new tag 'document-in-release-notes' or similar
 * draft in release notes as usual, cut/paste into github release
 * Add a diff between this release/previous to get #commits, #files #contributors or similar

**Comment by planetf1** [comment]
Also agreed on call 24 Mar that the Branch will be done on THURSDAY unless any objections are received
 - I will wait until after the status call to give another opportunity for maintainers to comment
 - The key features will be a) Audit Log Framework b) Tech preview of Repository Explorer

**Comment by planetf1** [comment]
CTs has now been run - and appears to pass.

For inmem:
```
Date of conformance test:          2020-04-06T12:55:42.674+0000
Number of tests that were run:     3955
Number of tests that failed:       0
Number of tests that were skipped: 0
```
```
	id	name	description	profilePriority	conformanceStatus
0	0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_PARTIAL_SUPPORT
5	5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
6	6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
9	9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	12	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	13	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	14	Relationship advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
```
And for local graph:
```
Date of conformance test:          2020-04-06T12:55:42.674+0000
Number of tests that were run:     3955
Number of tests that failed:       0
Number of tests that were skipped: 0
```
```
	id	name	description	profilePriority	conformanceStatus
0	0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
5	5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
6	6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
9	9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	12	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	UNKNOWN_STATUS
13	13	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
14	14	Relationship advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
```
@mandy-chessell @grahamwallis Please confirm these are as expected. Any issues we should track as a separate issue

**Comment by grahamwallis** [comment]
In-memory looks fine. 
Graph repo doesn't - can you please post/send the full results for graph?

**Comment by planetf1** [comment]
graph output: https://ibm.box.com/s/0vn03mhrqu94bcbxirn1zp48otf5oyiv

**Comment by planetf1** [comment]
Graph CTS results:
```
Date of conformance test:          2020-04-06T14:20:56.299+0000
Number of tests that were run:     3957
Number of tests that failed:       0
Number of tests that were skipped: 0
```
```
	id	name	description	profilePriority	conformanceStatus
0	0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
5	5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
6	6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
9	9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	12	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	13	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	14	Relationship advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT

```
