### ISSUE TITLE
Release 2.3

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3675]
Create 2.3 release (agreed on status call 24 Sep)

- [x] ✅ Create branch for 2.3 (PR not needed)
- [x] ✅ Reassign any issues not being worked on to the next release
- [x] ✅ Update master to **2.4-SNAPSHOT** 
- [x] ✅ Ensure any remaining fixes are merged #3684
- [x] ✅ Update branch version from 2.x-SNAPSHOT to 2.x 
- [x] ✅ Remove release notes from branch 
- [x] ✅ update release notes & rename #3669
- [x] ✅ Verify notebooks #3698
- [x] ✅ Check polymer UI (launches - but further tests not done, lacking example scenarios & lineage data)
- [x] ✅ Check node (ps) UI #3725 #3724 #3719 #3709 #3691 #3682
- [x] ✅ Run CTS (graph ok, inmem to be tested) #3741
- [x] ✅ Run FVTs (this is only FVTs automated in the build process)
- [x] ✅ Check samples (only samples in the build), utilities, client packaging [like 2.0 - there are issues we know of]
- [x] ✅ Check swagger doc #3699 
- [x] ✅ Verify docker image/charts/compose (vdc not tested, moving to samples repo)
- [x]  ✅ Launch release pipeline 
- [x]  ✅ Approve release
- [x] ⚠️ Verify artifacts all on maven central (check for JCenter & other errors in release logs)
- [ ] ✅ Create GitHub release
- [x] ✅ ensure any fixes ported to master

**Comment by planetf1** [comment]
Branch will be made 25 Sep AM (UK time) unless any issues notes.

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/issues/3669 for release note proposal

**Comment by planetf1** [comment]
CTS successful on graph & local following the update to the UBI image configuration
Other notebooks including asset, config, start, discovery all working as expected
Docs ok

**Comment by planetf1** [comment]
The release pipeline has now been started

**Comment by planetf1** [comment]
Surprisingly the release sync ran to completion within a single 6 hour run this time - perhaps as I kicked off at the weekend.

Current anomolies to address:
```
2020-10-04T08:19:46.2447010Z ##[section]Starting: Sync Missing Package to Maven-Central
2020-10-04T08:19:46.2482849Z ==============================================================================
2020-10-04T08:19:46.2483599Z Task         : Command line
2020-10-04T08:19:46.2484370Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-10-04T08:19:46.2488584Z Version      : 2.164.2
2020-10-04T08:19:46.2489100Z Author       : Microsoft Corporation
2020-10-04T08:19:46.2489585Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-10-04T08:19:46.2490140Z ==============================================================================
2020-10-04T08:19:46.4090600Z Generating script.
2020-10-04T08:19:46.4122454Z ========================== Starting Command Output ===========================
2020-10-04T08:19:46.4147114Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/006bcd4a-d1ff-459d-a9f5-9f0d51009614.sh
2020-10-04T08:19:46.4248938Z STARTING - Sync analytics-modeling-client:2.3
2020-10-04T08:19:46.7837094Z RESULT - Sync analytics-modeling-client:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:46.7868147Z STARTING - Sync data-engine-topic-connectors:2.3
2020-10-04T08:19:47.0081928Z RESULT - Sync data-engine-topic-connectors:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:47.0109388Z STARTING - Sync dev-ops-api:2.3
2020-10-04T08:19:47.1662323Z RESULT - Sync dev-ops-api:2.3 = {"message":"Version '2.3' was not found"}
2020-10-04T08:19:47.1686243Z STARTING - Sync digital-service-spring:2.3
2020-10-04T08:19:47.3676986Z RESULT - Sync digital-service-spring:2.3 = {"message":"Version '2.3' was not found"}
2020-10-04T08:19:47.3709529Z STARTING - Sync dino-view:2.3
2020-10-04T08:19:47.6167215Z RESULT - Sync dino-view:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:47.6196003Z STARTING - Sync dino-view-api:2.3
2020-10-04T08:19:47.8109637Z RESULT - Sync dino-view-api:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:47.8134708Z STARTING - Sync dino-view-server:2.3
2020-10-04T08:19:47.9795930Z RESULT - Sync dino-view-server:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:47.9823617Z STARTING - Sync dino-view-spring:2.3
2020-10-04T08:19:48.2654854Z RESULT - Sync dino-view-spring:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:48.2680274Z STARTING - Sync platform-services-client:2.3
2020-10-04T08:19:48.5072338Z RESULT - Sync platform-services-client:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:48.5117718Z STARTING - Sync presentation-server:2.3
2020-10-04T08:19:48.7031914Z RESULT - Sync presentation-server:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:48.7062172Z STARTING - Sync stewardship-engine-services-api:2.3
2020-10-04T08:19:48.8867895Z RESULT - Sync stewardship-engine-services-api:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:48.8899273Z STARTING - Sync stewardship-engine-services-client:2.3
2020-10-04T08:19:49.0621314Z RESULT - Sync stewardship-engine-services-client:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:49.0655983Z STARTING - Sync stewardship-engine-services-spring:2.3
2020-10-04T08:19:49.3332795Z RESULT - Sync stewardship-engine-services-spring:2.3 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
2020-10-04T08:19:49.3364384Z STARTING - Sync subject-area-fvt:2.3
2020-10-04T08:20:43.8139687Z RESULT - Sync subject-area-fvt:2.3 = {"status":"Validation Failed","messages":"[Missing: no javadoc jar found in folder '/org/odpi/egeria/subject-area-fvt/2.3', Dropping existing partial staging repository.]"}
2020-10-04T08:20:43.8168263Z 
2020-10-04T08:20:43.8255400Z ##[section]Finishing: Sync Missing Package to Maven-Central

```

**Comment by planetf1** [comment]
Of these
 - analytics modeling doesn't have a client -> NO ACTION
 - data-engine-topic-connectors -> new, so REQUESTED ADDITION 
 - dev-ops-api & digital-service-spring -- something ODD here as those artifacts not present -> INVESTIGATE MONDAY
 - dino-view* -> new. REQUESTED ADDITION
 - platform-services-client -> new. REQUESTED ADDITION
 - presentation-server -> new. REQUESTED ADDITION
 - stewardship-engine* - known. we've only had stubs for many releases. NO ACTION
 - subject-area-fvt -> This was supposedly fixed. twice :-( -> INVESTIGATE MONDAY

**Comment by planetf1** [comment]
It appears dev-ops-api and digital-service-spring are present on the JFrog artifactory 'egeria-release-local' repository - which is the final point the build distributes to, prior to requesting (automatically) they are pushed to bintray (also jfrog). Will look on monday at a) why this could have happened b) how to fix. From a cursory scan the scripts ran ok, so it could be a jfrog issue (we've had multiple before)

**Comment by grahamwallis** [comment]
Is presentation-server really new in 2.3?

**Comment by planetf1** [comment]
Release notes have been updated in #3670 including a reference to the missing maven artifacts

**Comment by planetf1** [comment]
> Is presentation-server really new in 2.3?

Probably debatable. did anyone have any chance of really using it before? And it wasn't packaged in anyway, so though it was indeed in the source tree,  it's effectively new as an end deliverable|?

**Comment by planetf1** [comment]
The release notes state:
```
Known Issues
Several maven artifacts have not been published to maven central/JCenter. See issue #3675 They can be retrieved from JFrog Artifactory at 'https://odpi.jfrog.io/odpi/egeria-release-local' if needed and it is not possible to build locally.
org.odpi.egeria:presentation-server
org.odpi.egeria:subject-area-fvt
org.odpi.egeria:dev-ops-api
org.odpi.egeria:digital-service-spring
```

Note that
```
org.odpi.egeria:dev-ops-api
org.odpi.egeria:digital-service-spring
```
have now been addressed by re-staging the artifacts from the release pipeline and re-distributing.

**Comment by planetf1** [comment]
2.3 has now shipped. closing
