### ISSUE TITLE
improvements in PR verifications & build 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3949]
Followup to https://github.com/odpi/egeria/issues/3940 - immediate issue resolved

- [x] The maven build is currently replicated for java 8 and java 11. In the UI when reviewing the output of actions one cannot easily distinguish between them without opening. Should consider either ensuring the naming is clearer/unique, or use a strategy matrix to execute builds across java 8 and 11 -> Fixed in #3964 
- [x] The Windows build addressed in #1307 is failing on azure pipelines due to long path restrictions, it would be worth trying actions for this build also -> will not do.
- [x] The new build in egeria-ui for node (and ultimately docker) is using pipelines. it may be worth considering actions. Await discussion and raise issue if required - https://github.com/odpi/egeria-ui/issues/47
- [x] The maven cache does not seem to be working, with this check taking so long it could be worth taking another look at - and similarly any suggestions on improving Java 11 build time -> Added in #3964 
- [x] Source is being built - since we don't use/test this, could be disabled (as it is in azure pipelines currently) - left as-is, to catch any packaging errors earlier.
- [x] The merge build, docker images are all done on azure pipelines. This is working and is less critical for a developer workflow, though now will be even more opaque. Should discuss/consider -- if so best to track as a new issue as there are many more moving parts including artifactory and docker hub. the release pipeline is also on azure (but distinct from merge build). If discussion is positive will open as new issue - see #4301
- [x] Only master is currently catered for. This should extend to all release & feature branches. Fixed in #3964
- [x] Gradle is extremely quick at incremental builds in identifying what has changed and the impacts. Unfortunately this does not yet run FVT tests and packaging, but the build times seen are a sign of what could be possible - see #3370 (not done yet)
- [x] We could add a PR build for windows - closing this See #1307 (dup of above)
- [x] Ideally we should have a PR build for docker containers - remains open in #1734 (not done yet)

**Comment by planetf1** [comment]
One option to speed checks further. Use java 8 only on maven and  11 for   gradle, as soon as fvts run under gradle? Still have coverage across both and may save  10 mins a cycle

**Comment by planetf1** [comment]
Opened up #3964 which catches most of the immediate updates needed to continue with github actions forward into the release. Topic to be discussed on the team call tomorrow.

**Comment by planetf1** [comment]
Note the attempt to rename hit an issue with the builds not being found, so is backed off

**Comment by planetf1** [comment]
Closing as individual issues now independently recorded/tracked
