### ISSUE TITLE
[RELEASE] Release 3.1

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5605]
### Work Plan

Create release 3.1 :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)
- [x] Remove release notes from branch
- [x] update release notes in master & rename

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [x] Create branch
- [x] Update version in master
- [x] Update version in new branch of connector, and of prereq egeria artifacts
- [x] Ensure new docker image is available for testing

Updating the Helm Charts
- [x] checker correct docker images are on dockerhub (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Run 'release' pipeline on egeria-reactui & validate artifacts
- [x] Create final github releases for egeria (use release notes from master as text)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Close repo on oss.sonatype.org for egeria-react ui
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [x] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [x] Create final github release
- PostGres Connector
  - [x] Create branch
  - [x] Update version in master
  - [x] Update version in new branch of connector, and of prereq egeria artifacts
  - [x] Create github release

**Comment by planetf1** [comment]
All tests are now complete. Release notes PR open. Running the final build for publishing.

**Comment by planetf1** [comment]
Egeria & Postgres connector published to maven central & docker
reactUI published to docker
Egeria, Postgres & ReactUI published to github

**Comment by planetf1** [comment]
Helm charts repo now updated

A reminder to install the lab charts:
```
helm repo add egeria https://odpi.github.io/egeria-charts
helm repo update && helm search repo egeria
helm install lab egeria/odpi-egeria-lab
```
