### ISSUE TITLE
[RELEASE] Release 3.2

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5698]
### Work Plan

Create release 3.2 :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)
- [x] Remove release notes from branch
- [x] update release notes in master & rename

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [x] Create branch
- [x] Update version in master
- [x] Update version in new branch of connector, and of prereq egeria artifacts
- [x] Ensure new docker image is available for testing

Updating the Helm Charts & docker-compose (egeria-charts repo)
- [x] checker correct docker images are on dockerhub (these are built by the 'merge' build of a release)
- n/a Update image versions for compose (egeria repo)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- n/a Verify docker compose (active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- n/a Run 'release' pipeline on egeria-reactui & validate artifacts
- [x] Create final github releases for egeria (use release notes from master as text)
- n/a Create final github release for egeria-ui
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- n/a Close repo on oss.sonatype.org for egeria-react ui
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [ ] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [x] Create final github release
- PostGres Connector
  - [x] Create branch
  - [x] Update version in master
  - [x] Update version in new branch of connector, and of prereq egeria artifacts
  - [x] Create github release

**Comment by planetf1** [comment]
Slack msg posted 21-Sep. 
Provisional agreement for branch (on 28 Sep) in developer call 23-Sep

**Comment by planetf1** [comment]
Final agreement will be requested on the team call Tue 28 Sep, with an intent to branch shortly thereafter.

**Comment by planetf1** [comment]
Agreed in dev call 28 Sep - exception being reported (correctly) when handling events with entities with attached memento or  ineffective dates.  Adding to readme+issue. Agreed to go ahead with release

**Comment by planetf1** [comment]
Ref above : https://github.com/odpi/egeria/issues/5717

**Comment by planetf1** [comment]
Note: need to add https://github.com/odpi/egeria/pull/5714 into the 3.2 release cc: @davidradl

**Comment by planetf1** [comment]
Issues noted in testing that are fairly noticeable in the labs:
 - Dino can't display a server config document https://github.com/odpi/egeria-react-ui/issues/264
 - getAssetSummary reporting exception https://github.com/odpi/egeria/issues/5722
  - getting known servers fails - https://github.com/odpi/egeria/issues/5023 (Existing issue)
  - firefox fails in dino https://github.com/odpi/egeria-react-ui/issues/96 (Existing issue)

**Comment by planetf1** [comment]
Quick (ie does it do something useful) test of egeria-UI (note this is not enabled by default in the coco environment)
 - Asset search works
 - Rex works
 - Tex works against https://lab-datalake:9443 / cocoMDS1

**Comment by planetf1** [comment]
CTS graph PASSED with
```
        "testCaseCount": 5569,
        "testFailedCount": 0,
        "testPassCount": 5569,
```
```
..... tbd
```
CTS inmem passed with:
```
        "class": "OpenMetadataConformanceTestLabResults",
        "testCaseCount": 5571,
        "testFailedCount": 0,
        "testPassCount": 5571,
```
```
name	description	profilePriority	conformanceStatus
0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_PARTIAL_SUPPORT
5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	Entity search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
```

**Comment by planetf1** [comment]
Samples test ok.

**Comment by planetf1** [comment]
The 3 new regressions listed above are all now fixed in egeria-react-ui 3.2 & in egeria 3.2 (as well as main/master)

**Comment by planetf1** [comment]
Correction - the issue with displaying config in the react UI is not fixed (lab & base). the others are.
WIll continue with release and add reference in release notes

**Comment by planetf1** [comment]
Egeria 3.2 is now released - artifacts are appearing on maven central (release) though may take a few hours to be indexed
Also egeria-react-ui & egeria-database-connectors are updated
Charts are now fully updated to release 3.2.0

**Comment by planetf1** [comment]
^ @cmgrote

**Comment by planetf1** [comment]
^ @CDaRip2U
