### ISSUE TITLE
[RELEASE] Release 3.3

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5828]
### Work Plan

Create release x.y :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)
- [x] Remove release notes from branch
- [x] update release notes in master & rename

Generate a release image for testing
- [x] Start release pipeline manually to generate docker image

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [x] Create branch
- [x] Update version in master
- [x] Update version in new branch 
- [x] Ensure new docker image is available for testing (there is no distinct release pipeline)

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct docker images are on dockerhub (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (use release notes from master as text)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [ ] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [x] Create final github release
- PostGres Connector
  - [x] Create branch
  - [x] Update version in master
  - [x] Update version in new branch of connector, and of prereq egeria artifacts
  - [x] Run release action, check sonatype & release
  - [x] Create github release

**Comment by planetf1** [comment]
CTS inmem:
```
        "testCaseCount": 5578,
        "testFailedCount": 0,
        "testPassCount": 5578,
```
```
name	description	profilePriority	conformanceStatus
0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_PARTIAL_SUPPORT
5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	Entity search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT

```

**Comment by planetf1** [comment]
CTS graph:
```
        "testCaseCount": 5578,
        "testFailedCount": 0,
        "testPassCount": 5578,
```
```
name	description	profilePriority	conformanceStatus
0	Metadata sharing	The technology under test is able to share met...	MANDATORY_PROFILE	CONFORMANT_FULL_SUPPORT
1	Reference copies	The technology under test is able to save, loc...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
2	Metadata maintenance	The technology under test supports requests to...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
3	Dynamic types	The technology under test supports changes to ...	OPTIONAL_PROFILE	UNKNOWN_STATUS
4	Graph queries	The technology under test supports graph-like ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
5	Historical search	The technology under test supports search for ...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
6	Entity proxies	The technology under test is able to store stu...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
7	Soft-delete and restore	The technology under test allows an instance t...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
8	Undo an update	The technology under test is able to restore a...	OPTIONAL_PROFILE	CONFORMANT_NO_SUPPORT
9	Reidentify instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
10	Retype instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
11	Rehome instance	The technology under test supports the command...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
12	Entity search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
13	Relationship search	The technology under test supports the ability...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
14	Entity advanced search	The technology under test supports the use of ...	OPTIONAL_PROFILE	CONFORMANT_FULL_SUPPORT
```

**Comment by planetf1** [comment]
Images tested fine after fixes. continuing with the release
