### ISSUE TITLE
Release 3.4

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5929]
### Work Plan

Create release 3.4 : 

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)
- [x] Remove release notes from branch
- [x] update release notes in master & rename

Generate a release image for testing
- [x] Start release pipeline manually to generate docker image

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [x] Create branch
- [x] Update version in master
- [x] Update version in new branch 
- [x] Ensure new docker image is available for testing (there is no distinct release pipeline)

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct docker images are on dockerhub (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (use release notes from master as text)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [ ] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [x] Create final github release
- PostGres Connector
  - [x] Create branch
  - [x] Update version in master
  - [x] Update version in new branch of connector, and of prereq egeria artifacts
  - [x] Run release action, check sonatype & release
  - [x] Create github release

**Comment by planetf1** [comment]
Agreed in Dev call 2021-11-23 that we will branch on 2021-11-29 (Monday)

**Comment by planetf1** [comment]
confirmed branch targetted at 2021-11-29 in team call 2021-11-25

**Comment by planetf1** [comment]
The branch has now been done & 2 PRs will be merged shortly to update the pom versions in master+branch.

**Comment by planetf1** [comment]
@sarbull @lpalashevski egeria-ui is currently at release 3.1.1 & under development
I presume you are planning to support 3.1.1 alongside egeria 3.4, and will update your dev release to a new release

**Comment by planetf1** [comment]
@sarbull @lpalashevski I also note there is no docker build for 3.1.1 since a month, and also no build for arm64 (which we'll need for the dojo). This is probably down to the optimization that was added for detecting if anything has changed, but this also may need to take into effect build changes. We'll need that sorted.

**Comment by lpalashevski** [comment]
> @sarbull @lpalashevski I also note there is no docker build for 3.1.1 since a month, and also no build for arm64 (which we'll need for the dojo). This is probably down to the optimization that was added for detecting if anything has changed, but this also may need to take into effect build changes. We'll need that sorted.

This is correct. We are in a process of finalizing the tests of the new changes (including the lab) then we are going to release new version which will trigger docker build with the new stable version. Keep you posted,

**Comment by planetf1** [comment]
@lpalashevski thanks. If we go up from 3.1.1, the version label in egeria-charts will need updating for the odpi-egeria-lab chart - you can do a PR or I can (also need to increment prerelease testing). I'll use that config for my testing. If intention is to stay at 3.1.1 then all should be fine once the new image is available.

We should check the arm64 image is created ok & is on quay etc- though I have no means to test it myself.

**Comment by lpalashevski** [comment]
This PR [egeria-ui#5929](https://github.com/odpi/egeria/issues/5929) once merged will bump the version and we will get new images created with tag 3.2.0. Once its there I will also test the labs and do PR for the charts to update the egeria-ui version.

**Comment by planetf1** [comment]
Additional fixes needed:
 - [ ] https://github.com/odpi/egeria-charts/issues/100

**Comment by planetf1** [comment]
CTS inmemory:
```
        "testCaseCount": 5612,
        "testFailedCount": 0,
        "testPassCount": 5612,

name | description | profilePriority | conformanceStatus
-- | -- | -- | --
Metadata sharing | The technology under test is able to share met... | MANDATORY_PROFILE | CONFORMANT_FULL_SUPPORT
Reference copies | The technology under test is able to save, loc... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Metadata maintenance | The technology under test supports requests to... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Dynamic types | The technology under test supports changes to ... | OPTIONAL_PROFILE | UNKNOWN_STATUS
Graph queries | The technology under test supports graph-like ... | OPTIONAL_PROFILE | CONFORMANT_PARTIAL_SUPPORT
Historical search | The technology under test supports search for ... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Entity proxies | The technology under test is able to store stu... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Soft-delete and restore | The technology under test allows an instance t... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Undo an update | The technology under test is able to restore a... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Reidentify instance | The technology under test supports the command... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Retype instance | The technology under test supports the command... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Rehome instance | The technology under test supports the command... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Entity search | The technology under test supports the ability... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Relationship search | The technology under test supports the ability... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Entity advanced search | The technology under test supports the use of ... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT


```

CTS graph
```
        "testCaseCount": 5612,
        "testFailedCount": 0,
        "testPassCount": 5612,

name | description | profilePriority | conformanceStatus
-- | -- | -- | --
Metadata sharing | The technology under test is able to share met... | MANDATORY_PROFILE | CONFORMANT_FULL_SUPPORT
Reference copies | The technology under test is able to save, loc... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Metadata maintenance | The technology under test supports requests to... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Dynamic types | The technology under test supports changes to ... | OPTIONAL_PROFILE | UNKNOWN_STATUS
Graph queries | The technology under test supports graph-like ... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Historical search | The technology under test supports search for ... | OPTIONAL_PROFILE | CONFORMANT_NO_SUPPORT
Entity proxies | The technology under test is able to store stu... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Soft-delete and restore | The technology under test allows an instance t... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Undo an update | The technology under test is able to restore a... | OPTIONAL_PROFILE | CONFORMANT_NO_SUPPORT
Reidentify instance | The technology under test supports the command... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Retype instance | The technology under test supports the command... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Rehome instance | The technology under test supports the command... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Entity search | The technology under test supports the ability... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Relationship search | The technology under test supports the ability... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT
Entity advanced search | The technology under test supports the use of ... | OPTIONAL_PROFILE | CONFORMANT_FULL_SUPPORT


```

**Comment by lpalashevski** [comment]
Egeria UI version 3.2.0 works as expected. Tested on local k8s using lab charts tag: 3.4.0-prerelease.0
Good to proceed.

**Comment by planetf1** [comment]
Other than communications, the release of egeria/egeria-ui/egeria-react-ui/egeria-database-connectors is complete

@cmgrote should be good for additional connectors
