### ISSUE TITLE
[RELEASE] Release 3.6

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6228]
### Work Plan

Create release x.y :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)

Generate a release image for testing
- [x] Start release pipeline manually to generate container image

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [n/a] Create branch
- [n/a] Update version in master
- [n/a] Update version in new branch 
- [n/a] Ensure new container image is available for testing (there is no distinct release pipeline)

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on docker.io & quay.io (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final Docs
- [ ] Update release notes in egeria-docs

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (add link to egeria docs)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [ ] Additional posts to social media
- [ ] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [n/a] Create final github release
- PostGres Connector
  - [n/a] Create branch
  - [n/a] Update version in master
  - [n/a] Update version in new branch of connector, and of prereq egeria artifacts
  - [n/a] Run release action, check sonatype & release
  - [n/a] Create github release

**Comment by planetf1** [comment]
I propose to discuss in the next call on 2022-02-22 & that we branch later this week - ideally Thu or Fri

**Comment by planetf1** [comment]
Agreed in developer call 2022-02-24 that we will branch today
 - Same version of react UI as previous release (3.5.0) - as no changes
 - same version of business UI as previous release (3.2.0) - no changes due to refactoring of UI

**Comment by planetf1** [comment]
@cmgrote mentioned on dev call there were some issues seen with CTS for xtdb when run from the helm chart, whilst all worked ok when run via notebook. I will therefore first run the CTS across mem/graph via notebook as usual, but also try cts across all 3 repos (including xtdb) via the chart.

**Comment by planetf1** [comment]
Notebooks/charts all ok, other than some changes to failures noted in #5021. This is on incomplete work/notebook with a known issue so should not be a concern. WIll verify.

**Comment by planetf1** [comment]
CTS test results (graph):
```
        "testCaseCount": 5703,
        "testFailedCount": 1,
        "testPassCount": 5702,
```

The failing list assertion is:
```
                            "repository-relationship-property-search-10: findRelationshipsByProperty found 2/1 expected results using parameters: {asOfTime=null, fromRelatio
nshipElement=0, limitResultsByStatus=null, matchCriteria=All, matchProperties=InstanceProperties{propertyNames=java.util.HashMap$KeyIterator@6cd6798c, propertyCount=1, insta
nceProperties={deployer=PrimitivePropertyValue{primitiveValue=\\Qdeployer.1\\E, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.St
ring', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}
, typeGUID='null', typeName='null'}}}, pageSize=10, relationshipTypeGUID=2480aa71-44c5-414d-8b32-9c4340786d77, sequencingOrder=null, sequencingProperty=null}"
```
Will also run inmem and investigate
cc:

**Comment by planetf1** [comment]
The above issue didn't re-occur. It's possible the test started slightly too early before kafka was fully up (there may be a startup issue .. but if so it's probably a long-running issue, or strimzi specific, rather than new)

However the inmemory cts also failed with the same error as above
```
                        "unsuccessfulAssertions": [
                            "repository-relationship-property-search-10: findRelationshipsByProperty found 2/1 expected results using parameters: {asOfTime=null, fromR
elationshipElement=0, limitResultsByStatus=null, matchCriteria=All, matchProperties=InstanceProperties{propertyNames=java.util.HashMap$KeyIterator@5715f6c6, propertyCo
unt=1, instanceProperties={deployer=PrimitivePropertyValue{primitiveValue=\\Qdeployer.1\\E, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClass
Name='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescript
ion='A primitive type.'}, typeGUID='null', typeName='null'}}}, pageSize=10, relationshipTypeGUID=2480aa71-44c5-414d-8b32-9c4340786d77, sequencingOrder=null, sequencing
Property=null}"
```
cc: @mandy-chessell

**Comment by planetf1** [comment]
The xtdb test completed with failures -- however quite different, and most likely an xtdb related issue. These aren't normally tested for a release so will not block this release on that basis. The issue can be found at https://github.com/odpi/egeria-connector-xtdb/issues/319

**Comment by cmgrote** [comment]
I think most of the failures you ran into with the XT connector are from the last release -- there was a bug that's been fixed but is only currently in the SNAPSHOT builds. I'm seeing the same `repository-relationship-property-search-10` failure, against the same relationship type.

I've noted that this relationship type (`SupportedSoftwareCapability`) is new in the 3.6 release, and more interestingly that in the same `OpenMetadataTypesArchive` there is:
- a deprecated relationship (`SoftwareServerSupportedCapability`)
- the TypeDefPatch that does the deprecation sets the _supertype_ of the deprecated relationship to `SupportedSoftwareCapability`

I _think_ this is the very first time that we're using super types anywhere for relationships? (I know we had mentioned the idea in a previous issue and started a feature branch, but that was never finalized.) I suspect it's this super-typing of a relationship that's throwing off the way the CTS has currently been written -- I don't think the CTS has anticipated that super types would be used for relationships... (It's also quite plausible that none of the repositories are currently handling super typed relationships, either, as I don't think they've ever been tested for this scenario.)

Is there any particular reason why we're trying to introduce relationship super types for the very first time on a _deprecated_ relationship typedef (this seems strange)?

```java
    private TypeDefPatch deprecateSoftwareServerSupportedCapabilityRelationship()
    {
        /*
         * Create the Patch
         */
        final String typeName = "SoftwareServerSupportedCapability";
        final String superTypeName = "SupportedSoftwareCapability";

        TypeDefPatch  typeDefPatch = archiveBuilder.getPatchForType(typeName);

        typeDefPatch.setUpdatedBy(originatorName);
        typeDefPatch.setUpdateTime(creationDate);
        typeDefPatch.setSuperType(this.archiveBuilder.getRelationshipDef(superTypeName));
        typeDefPatch.setTypeDefStatus(TypeDefStatus.DEPRECATED_TYPEDEF);

        return typeDefPatch;
    }
```

**Comment by cmgrote** [comment]
It's also not clear to me why that's suddenly coming up for all of these repositories now, as it looks like the `OpenMetadataTypeArchive` file has not been updated in the last 2 months, which would imply this super type change was actually there in the 3.5 release as well (?)

(Also I note that we have not marked the `OpenMetadataTypesArchive3_5` file for the 3.6 release, which presumably we need to do even if there were no changes to the `OpenMetadataTypesArchive` file itself for the 3.6 release, so that we don't lose track of which type changes were included in which release?)

**Comment by mandy-chessell** [comment]
On the archive, we have not in the past created empty archive files for releases where there have been no type changes.  There have not been many instances of this :)

Looking at the type definition, the impact of removing the inheritance is that IT Infrastructure OMAS will need to ensure it issues retrieve requests for both relationships when retrieving the capabilities of a server.   However, if we are not ready for inheritied relationshhips yet in the CTS/repositories then we should remove it and I will make changes to IT Infrastructure OMAS in 3.7.  I do not think we need to do this in the 3.6 branch because IT Infrastructure OMAS is still in development.

**Comment by planetf1** [comment]
On above point -- mandy, thanks for pointing out that change went in to 3.5 also. I checked the results from 3.5, and we did not have a test failure so either
 - the failure is intermittent
 - the failure is caused by another change
 - something else has changed in the infrastructure/dependencies to cause a failure

**Comment by planetf1** [comment]
The failing test case is listed as `findRelationshipsByProperty with regex to match set 0 NONE returned no unexpected relationships.` . The property search is on string. How do we match this to a specific type being tested?

**Comment by cmgrote** [comment]
It does seem that this failure is intermittent -- I've been able to run the CTS successfully and unsuccessfully for exactly the same code and parameters. I believe this is due to the CTS picking properties to test for search in a non-deterministic way, e.g. the first it finds in a hashmap, which isn't ordered so will vary from one run to another.

I _think_ the trick is whether the property it picks to test happens to exist at multiple levels of the inheritance hierarchy or not -- if it does, I believe it'll result in this kind of issue; while if it does not, then this issue may be missed due to simple luck. (It just happens that the particular relationship I flagged only has _one_ property (out of 3) that does not have this kind of overlap between super and subtype -- so odds are more in favor of hitting the error than not.)

See #6290 for some initial changes in this direction, as discussed previously...

I'm going to re-test locally with removing the attributes from the now-child relationship the same way as I've done for the others in #6290 and see if that resolves this problem as well (for now) in the CTS.

**Comment by planetf1** [comment]
Graph CTS now passes 
```

   "testCaseCount": 5703,
        "testFailedCount": 0,
        "testPassCount": 5703,
```

**Comment by planetf1** [comment]
in-memory CTS passed
```
        "testCaseCount": 5703,
        "testFailedCount": 0,
        "testPassCount": 5703,
```

**Comment by planetf1** [comment]
Release 3.6 done, though curated release notes still to do.

**Comment by planetf1** [comment]
cc: @cmgrote

**Comment by planetf1** [comment]
This is now complete - no further specific work planned on 3.6
