### ISSUE TITLE
[RELEASE] Release 3.9

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6539]
### Work Plan

Create release 3.9 :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)

Generate a release image for testing
- [x] Start release pipeline manually to generate container image

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [N/A] Create branch
- [N/A] Update version in master
- [N/A] Update version in new branch 
- [N/A] Ensure new container image is available for testing (there is no distinct release pipeline)

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on docker.io & quay.io (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final Docs
- [x] Update release notes in egeria-docs

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (add link to egeria docs)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [x] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [N/A] Create final github release
- PostGres Connector
  - [N/A] Create branch
  - [N/A] Update version in master
  - [N/A] Update version in new branch of connector, and of prereq egeria artifacts
  - [N/A] Run release action, check sonatype & release
  - [N/A] Create github release

**Comment by planetf1** [comment]
I would like to propose we branch for the release on Thu 26 May.

**Comment by planetf1** [comment]
Agreed in face2face meeting AMS that we will do the branch on 26 May

**Comment by planetf1** [comment]
@davidradl I will do an initial version of our helm charts using the 3.8.1 version of the UI.
If you plan to make a 3.9 release, we can update the pre-release charts for testing to use the 3.9.0-rc version when avail. Please let me know which works for you.

**Comment by planetf1** [comment]
prerelease charts now available for testing:
```
helm repo update && helm search repo egeria  --devel
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "strimzi" chart repository
...Successfully got an update from the "egeria" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME                  	CHART VERSION     	APP VERSION	DESCRIPTION                                       
egeria/egeria-base    	3.9.0-prerelease.0	3.9        	Egeria simple deployment (platform, react UI)     
egeria/egeria-cts     	3.9.0-prerelease.0	3.9        	Egeria Conformance Test Suite deployment to Kub...
egeria/egeria-pts     	3.9.0-prerelease.0	3.9        	Egeria Performance Test Suite deployment to Kub...
egeria/odpi-egeria-lab	3.9.0-prerelease.0	3.9        	Egeria lab environment        
```

**Comment by planetf1** [comment]
The following issues were raised during testing:
* #6548 
* #6549 
* #6550 
* odpi/egeria-docs#444

However none are critical or known regressions in stable code, so will not impact release

**Comment by planetf1** [comment]
#6547 was also recently opened - the ui-lab fails to locate assets due to being in wrong zone - but it's likely this has been there in previous releases as this lab needs more elaboration. In addition the UI code level in the charts is back at 3.2.0 since the code is being refactored, so will leave as-is for the release

**Comment by planetf1** [comment]
First cts test run (inmemory) has failed
```
    "testLabResults": {
        "class": "OpenMetadataConformanceTestLabResults",
        "testCaseCount": 5826,
        "testFailedCount": 1,
        "testPassCount": 5825,
        "testResultsFromWorkbenches": [
            {
                "class": "OpenMetadataConformanceWorkbenchResults",
                "failedTestCases": [
                    {
                        "class": "OpenMetadataTestCaseResult",
                        "conformanceException": {
                            "errorMessage": "CTS test repository-entity-reference-copy-lifecycle caught exception EntityNotKnownException from method getEntityDetail whilst trying to retrieve an entity of type APISchemaType.  Exception message was : OMRS-REPOSITORY-404-002 The entity identified with guid 3709ed6f-01c7-4901-bf6f-cdc8cba05334 passed on the getEntityDetail call is not known to the open metadata repository tut.  Method was invoked with parameters: entityGUID : 3709ed6f-01c7-4901-bf6f-cdc8cba05334",
                            "exceptionClassName": "java.lang.Exception"
                        },
                        "notSupportAssertions": [],
                        "successfulAssertions": [
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
                            "repository-entity-reference-copy-lifecycle-00: APISchemaType entity type definition matches known type  ",
                            "repository-entity-reference-copy-lifecycle-01: APISchemaType reference entity created; repository supports storage of reference copies.",
                            "repository-entity-reference-copy-lifecycle-02: APISchemaType reference entity can be retrieved as EntitySummary.",
                            "repository-entity-reference-copy-lifecycle-03: APISchemaType reference entity can be retrieved as EntityDetail.",
                            "repository-entity-reference-copy-lifecycle-04: APISchemaType reference entity matches the entity that was saved.",
                            "repository-entity-reference-copy-lifecycle-05: APISchemaType reference entity has no relationships.",
                            "repository-entity-reference-copy-lifecycle-06: APISchemaType reference entity status cannot be updated.",
                            "repository-entity-reference-copy-lifecycle-06: APISchemaType reference entity status cannot be updated.",
                            "repository-entity-reference-copy-lifecycle-07: APISchemaType reference entity properties cannot be updated.",
                            "repository-entity-reference-copy-lifecycle-08: APISchemaType reference entity type cannot be changed.",
                            "repository-entity-reference-copy-lifecycle-09: APISchemaType reference entity identity cannot be changed.",
                            "repository-entity-reference-copy-lifecycle-10: APISchemaType reference entity copy purged at TUT.",
                            "repository-entity-reference-copy-lifecycle-11: APISchemaType reference entity refresh requested by TUT.",
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite."
                        ],
                        "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-entity-reference-copy-lifecycle-test-case.md",
                        "testCaseId": "repository-entity-reference-copy-lifecycle-APISchemaType",
                        "testCaseName": "Repository entity reference copy lifecycle test case",
                        "unsuccessfulAssertions": [
                            "Unexpected Exception Exception : CTS test repository-entity-reference-copy-lifecycle caught exception EntityNotKnownException from method getEntityDetail whilst trying to retrieve an entity of type APISchemaType.  Exception message was : OMRS-REPOSITORY-404-002 The entity identified with guid 3709ed6f-01c7-4901-bf6f-cdc8cba05334 passed on the getEntityDetail call is not known to the open metadata repository tut.  Method was invoked with parameters: entityGUID : 3709ed6f-01c7-4901-bf6f-cdc8cba05334"
                        ]
                    }
                ],
                "passedTestCases": [
```

**Comment by planetf1** [comment]
poll counts were doubled in 7e4a90952fdd9373ef808bbc59f5869be033ec1a

**Comment by planetf1** [comment]
@mandy-chessell ^^ let's discuss early next week

**Comment by planetf1** [comment]
Initial release notes for 3.9 added. Any additions please submit a PR on egeria-docs

**Comment by planetf1** [comment]
Agreed in team call 2021-05-31 :
 - Add notes on the cts, cohort registration #6353, discovery issues (at a minimum) to the release notes
 - Continue to ship the release
 - Investigate these three issues further in the next week

**Comment by planetf1** [comment]
Will plan to do a bigger blog/announce for the 3.10 release to round-up the first part of the year's content
