### ISSUE TITLE
[RELEASE] Release 3.10

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6554]
### Work Plan

Create release 3.10 :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)

Generate a release image for testing
- [x] Start release pipeline manually to generate container image

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [n/a] Create branch
- [n/a ] Update version in master
- [n/a ] Update version in new branch 
- [n/a ] Ensure new container image is available for testing (there is no distinct release pipeline)

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on docker.io & quay.io (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final Docs
- [x] Update release notes in egeria-docs

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (add link to egeria docs)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [x] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [n/a] Create final github release
- PostGres Connector
  - [n/a] Create branch
  - [n/a] Update version in master
  - [n/a] Update version in new branch of connector, and of prereq egeria artifacts
  - [n/a] Run release action, check sonatype & release
  - [n/a] Create github release

**Comment by planetf1** [comment]
Planned for end June 2022

**Comment by planetf1** [comment]
Agreed in developers call 2022-06-21 that we would target Monday 27 June for the next branch in prep for ~1 July release.

Also agreed that we would not plan to ship a 1 August release, but would take a summer break, with the release targetted for ~1 September. If we have specific fixes/features or major bugs, then we can revisit this and release if needed.

Currently plan to ship with
* egeria-react-ui 3.8.0 (no significant code changes since) cc: @davidradl 
* egeria-ui 3.2.0 (prior to refactoring which is in progress) cc: @sarbull

**Comment by planetf1** [comment]
@mandy-chessell I know we have some changes you wish to get into 3.10. If you have any PRs awaiting review, or when you are ready please confirm so I can branch - no earlier than Monday, but can wait a few more days if needed.

**Comment by planetf1** [comment]
Agreed on developer call 2022-06-22 that we will branch today

The previously identified fix (to deduplication) needs more fixes & testing, and will be targetted at the 1 Sep release

**Comment by planetf1** [comment]
CTS Results - same as last release.
InMemory - fails with 1 error. 
Graph - all ok
**InMemory results:**
```
        "testCaseCount": 5826,
        "testFailedCount": 1,
        "testPassCount": 5825,
```
```
jq '.testLabSummary.testSummariesFromWorkbenches[].profileSummaries[] | { profile: .name, status: .conformanceStatus }' openmetadata_cts_summary.json
{
  "profile": "Metadata sharing",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Reference copies",
  "status": "NOT_CONFORMANT"
}
{
  "profile": "Metadata maintenance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Dynamic types",
  "status": "UNKNOWN_STATUS"
}
{
  "profile": "Graph queries",
  "status": "CONFORMANT_PARTIAL_SUPPORT"
}
{
  "profile": "Historical search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity proxies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Soft-delete and restore",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Undo an update",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Reidentify instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Retype instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Rehome instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
```

**Graph results:**
```
        "testCaseCount": 5826,
        "testFailedCount": 0,
        "testPassCount": 5826,
        
        
jq '.testLabSummary.testSummariesFromWorkbenches[].profileSummaries[] | { profile: .name, status: .conformanceStatus }' openmetadata_cts_summary.json
{
  "profile": "Metadata sharing",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Reference copies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Metadata maintenance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Dynamic types",
  "status": "UNKNOWN_STATUS"
}
{
  "profile": "Graph queries",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Historical search",
  "status": "CONFORMANT_NO_SUPPORT"
}
{
  "profile": "Entity proxies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Soft-delete and restore",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Undo an update",
  "status": "CONFORMANT_NO_SUPPORT"
}
{
  "profile": "Reidentify instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Retype instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Rehome instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
```

**Comment by planetf1** [comment]
Adding fix for #6638 to release 3.10 .

This fix is needed for some production deployments & at least two orgs need such capability.

Tests have been completed on master, but I’ll rerun one of the cts (lots of kafka) and notebooks to guard against regressions.

**Comment by planetf1** [comment]
Retests all successful

Originally in issue: https://github.com/odpi/egeria/issues/6549#issuecomment-1141012770

**Comment by planetf1** [comment]
After initial review of #6549 it appears there are cohort registration issue.

At this time I WILL NOT RELEASE 3.10 until we understand more about this issue.

**Comment by planetf1** [comment]
Retested following cohort fix
 - Lab notebooks
 - CTS (inmemory)
 
 All look good with a complete cohort and no cts problems.
 
 Going forward with release

**Comment by planetf1** [comment]
Release now shipped
