### ISSUE TITLE
[RELEASE] Release 3.11

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6812]
### Work Plan

Create release 3.11 :

Prior to the release work
- [ ] slack post advising of upcoming release & linking to issue
- [ ] advance warning in developer/community call
- [ ] final agreement to start branch in team call & identification of outstanding issues
- [ ] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [ ] Create branch
- [ ] Reassign any issues not being worked on to the next release
- [ ] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [ ] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [ ] Ensure any remaining fixes are merged into branch (and vice-versa to master)

Generate a release image for testing
- [ ] Start release pipeline manually to generate container image

Updating the React UI (as this is part of the notebook test). Note egeria-ui is out of scope other than inclusion of current release
- [ ] Create branch
- [ ] Update version in master
- [ ] Update version in new branch 
- [ ] Ensure new container image is available for testing (there is no distinct release pipeline)

Updating the Helm Charts (egeria-charts repo)
- [ ] checker correct container images are on docker.io & quay.io (these are built by the 'merge' build of a release)
- [ ] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [ ] Check swagger doc renders (no regressions)
- [ ] Verify odpi-egeria-lab chart (pods active/ready)
- [ ] Verify egeria-base chart (pods active/ready)
- [ ] Check notebooks (config, start, data catalog at a minimum)
- [ ] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [ ] Check React UI (rex, tex, glossary author)
- [ ] CTS - graph
- [ ] CTS - inmemory

Final Docs
- [ ] Update release notes in egeria-docs

Final build and publish
- [ ] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [ ] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [ ] Create final github releases for egeria (add link to egeria docs)
- [ ] Close repo on oss.sonatype.org (once updated) for egeria, release
- [ ] Check 'release' repo on oss.sonatype.org has artifacts
- [ ] Update final versions of egeria-charts to release ie x.y
- [ ] Publish that release is now shipped via slack #egeria-announce
- [ ] Additional posts to social media
- [ ] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Additional components
- ReactUI
  - [ ] Create final github release
- Egeria Dev Projects
  - [ ] Update project & dependency versions to new release

Get Ready for next release
- [ ] Open Release Issue for next release

**Comment by planetf1** [comment]
I propose to branch for release 3.11 on Thu 25 August, for a release ~1 Sep

**Comment by planetf1** [comment]
For our helm charts:
@lpalashevski @sarbull I assume we are staying with egeria-ui 3.2.0 (old) and @davidradl we stick with egeria-react-ui 3.8.0.
The new Jupyter notebook environment will be used cc: @mandy-chessell

**Comment by planetf1** [comment]
As per slack discussion, the release branch is now targeted as the morning of 30 August.
The release should be available early September

**Comment by planetf1** [comment]
Egeria branch and release work now underway

**Comment by planetf1** [comment]
@lpalashevski @davidradl As above, presuming no change in versions for either UI component compared to release 3.10

**Comment by planetf1** [comment]
* lab notebooks generally OK
* React UI same as previously - bugs, but already reported
* Business UI - *NOT WORKING* (nginx appears to close connection immediately)
* CTS - running

**Comment by planetf1** [comment]
CTS clean apart from 1 intermittent issue seen for a few releases with:
```
                     "unsuccessfulAssertions": [
                            "Unexpected Exception Exception : CTS test repository-entity-reference-copy-lifecycle caught exception EntityNotKnownException from method getEntityDet
ail whilst trying to retrieve an entity of type APISchemaType.  Exception message was : OMRS-REPOSITORY-404-002 The entity identified with guid 772bce12-0e80-4766-b7ef-3432f5b7320
4 passed on the getEntityDetail call is not known to the open metadata repository tut.  Method was invoked with parameters: entityGUID : 772bce12-0e80-4766-b7ef-3432f5b73204"
```
This is believed to be timing related                         ]

**Comment by planetf1** [comment]
Opened https://github.com/odpi/egeria-charts/issues/187 to track issue with Business UI not loading

**Comment by planetf1** [comment]
Issue was with LoadBalancer. Now tested ok on openshift & rancher using port-forward.
