### ISSUE TITLE
Release 3.13

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6988]
### Work Plan

Create release x.y :

Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [ ] Reassign any issues not being worked on to the next release
- [x] Update version for master (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to master)

Generate a release image for testing
- [x] Start release pipeline manually to generate container image

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on docker.io & quay.io (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts (egeria-charts repo) (using -prerelease for chart version)

Final tests
- [x] Check swagger doc renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs - no demo scenario for more)
- [x] Check React UI (rex, tex, glossary author)
- [x] CTS - graph
- [x] CTS - inmemory

Final Docs
- [x] Update release notes in egeria-docs

Final build and publish
- [x] Run 'release' pipeline on branch to push candidates to oss.sonatype.org
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (add link to egeria docs)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [ ] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed

Get Ready for next release
- [ ] Open Release Issue for next release

**Comment by planetf1** [comment]
**RELEASE NOTES**

As of this release, the release notes will be written by date, ie
'November 2022' which will then list all the major updates done during the prior month - ie the development for Egeria 3.13, but also updates to UIs, connectors, docs, community.

cc: @mandy-chessell

**Comment by planetf1** [comment]
Planning to BRANCH for this on ~31 October. (cc: @lpalashevski )

**Comment by planetf1** [comment]
@lpalashevski have added comment

**Comment by mandy-chessell** [comment]
@planetf1 @lpalashevski  Here is the monthly newsletter https://egeria-project.org/release-notes/october-2022/
this is the current state of the 3.13 release notes: https://egeria-project.org/release-notes/next/.

I suggest continue to have a page for each Egeria Core release listing the updates and fixes - and then link to it from the monthly newsletter.  WE plan to review it on the community call this week.

**Comment by planetf1** [comment]
As we have the meeting shortly, I generated a list of PRs that we have included in 3.13:

* #6898 Update version to 3.13-SNAPSHOT by @planetf1 in https://github.com/odpi/egeria/pull/6903
* Added ProcessingState classification and endpoints to upsert it by @MihaiIliescu in https://github.com/odpi/egeria/pull/6620
* Update Data Manager OMAS REST API; Begin Digital Service OMAS API by @mandy-chessell in https://github.com/odpi/egeria/pull/6908
* Add data product types (#6526) by @mandy-chessell in https://github.com/odpi/egeria/pull/6976
* #6803 add scorecards check by @planetf1 in https://github.com/odpi/egeria/pull/6979
* Dependabot 20221003 by @planetf1 in https://github.com/odpi/egeria/pull/6980
* Add ability to override AL OMAS topic listener connection properties by @popa-raluca in https://github.com/odpi/egeria/pull/6900
* Bump kafka-clients from 3.3.0 to 3.3.1 by @dependabot in https://github.com/odpi/egeria/pull/6984
* Bump kafka-clients from 3.3.0 to 3.3.1 by @dependabot in https://github.com/odpi/egeria/pull/6982
* #6803 fix scorecards yaml by @planetf1 in https://github.com/odpi/egeria/pull/6985
* Add versionIdentifier and initial Digital Service OMAS APIs by @mandy-chessell in https://github.com/odpi/egeria/pull/6986
* Vertical lineage query for Glossary & GlossaryCategory by @marius-patrascu in https://github.com/odpi/egeria/pull/6906
* Change Software Server Capability to more specific type - Engine by @MihaiIliescu in https://github.com/odpi/egeria/pull/6993
* #6994 Revert slf4j-api version - 3.12 regression preventing spring de… by @planetf1 in https://github.com/odpi/egeria/pull/6995
* #7004 add Dan as contributor by @planetf1 in https://github.com/odpi/egeria/pull/7005
* Add typedefs and instances to JavaDoc by @mandy-chessell in https://github.com/odpi/egeria/pull/7006
* Gradle: create maven artifacts by @planetf1 in https://github.com/odpi/egeria/pull/7007
* #6907 master->main rename by @planetf1 in https://github.com/odpi/egeria/pull/7042
* odpi/egeria#6907 further updates master->main by @planetf1 in https://github.com/odpi/egeria/pull/7046
* Update demo users for the Egeria UI by @mandy-chessell in https://github.com/odpi/egeria/pull/7047
* More details on configuring role/component visibility in the polymer ui. by @lpalashevski in https://github.com/odpi/egeria/pull/7048
* Various fixes by @mandy-chessell in https://github.com/odpi/egeria/pull/7054
* Third party transitive depdendency updates  by @lpalashevski in https://github.com/odpi/egeria/pull/7003
* Egeria release 3.13 by @lpalashevski in https://github.com/odpi/egeria/pull/7062


**Full Changelog**: https://github.com/odpi/egeria/compare/V3.12...V3.13

**Comment by planetf1** [comment]
Additional reminders of checks needed each release that are not covered in the current docs or checklists but that I've been doing (all now done for 3.13 thanks @lpalashevski ):

* Check/update the strimzi chart versions
* check/update the kafka version used for the strimzi CR in each chart
* check/update the current jupyter lab version & generate a new docker container in egeria-jupyter
* Update the jupyter lab version in the charts

**Comment by lpalashevski** [comment]
CTS Results

GraphRepo Run summary:
```
{
  "testCaseCount": 6104,
  "testPassCount": 6104,
  "testFailedCount": 0,
  "testSkippedCount": 0
}

```
GraphRepo Profile:
```
{
  "profile": "Metadata sharing",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Reference copies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Metadata maintenance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Dynamic types",
  "status": "UNKNOWN_STATUS"
}
{
  "profile": "Graph queries",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Historical search",
  "status": "CONFORMANT_NO_SUPPORT"
}
{
  "profile": "Entity proxies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Soft-delete and restore",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Undo an update",
  "status": "CONFORMANT_NO_SUPPORT"
}
{
  "profile": "Reidentify instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Retype instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Rehome instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}

```

InMemory Run summary:
```
{
  "testCaseCount": 6104,
  "testPassCount": 6104,
  "testFailedCount": 0,
  "testSkippedCount": 0
}
```

inMemory Profile:
```
{
  "profile": "Metadata sharing",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Reference copies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Metadata maintenance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Dynamic types",
  "status": "UNKNOWN_STATUS"
}
{
  "profile": "Graph queries",
  "status": "CONFORMANT_PARTIAL_SUPPORT"
}
{
  "profile": "Historical search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity proxies",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Soft-delete and restore",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Undo an update",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Reidentify instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Retype instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Rehome instance",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Entity advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
{
  "profile": "Relationship advanced search",
  "status": "CONFORMANT_FULL_SUPPORT"
}
```

**Comment by lpalashevski** [comment]
Closing the issue as the release 3.13 is complete now.
