### ISSUE TITLE
[RELEASE]Release 4

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7553]
### Work Plan

Create release 4.0 :
Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [x] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [x] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for main (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to main)

Pre-release security check
- [x] Execute manual [sonatype lift scan](https://lift.sonatype.com) on release branch from and communicate findings (needs more formal process in future)

Generate a release image for testing
- [x] Start [Release](https://github.com/odpi/egeria/actions/workflows/release.yml) pipeline manually to generate container image

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on [docker.io](https://hub.docker.com/u/odpi) & [quay.io](https://quay.io/organization/odpi) (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts [egeria-charts](https://github.com/odpi/egeria-charts/) repo (using -prerelease for chart version)
  - check/update the strimzi chart versions
  - check/update the kafka version used for the strimzi CR in each chart
  - check/update the current jupyter lab version & generate a new docker container in egeria-jupyter
  - update the jupyter lab version in the charts

Final tests
- [x] Check [swagger doc](https://egeria-project.org/education/tutorials/swagger-tutorial/overview/?h=swagger) renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs and run UI lab)
- [x] Check React UI (rex, tex, glossary author). Some of the steps descibed [here](https://egeria-project.org/education/egeria-dojo/running-egeria/user-interfaces/ecosystem-ui/ecosystem-ui-start/)
- [x] [CTS - graph](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)
- [x] [CTS - inmemory](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)

Final Docs
- [x] Update release notes in egeria-docs

Final build and publish
- [x] Check if the Release pipeline rlease artifacts are shown in staging repo in [OSS Repository Manager](https://oss.sonatype.org/#welcome)
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (add link to egeria docs)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [x] Post on egeria-annouce [mailing list](egeria-announce@lists.lfaidata.foundation)
- [x] Additional posts to social media
- [x] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed (Egeria Dev Projects etc.)

Get Ready for next release
- [x] Open Release Issue for next release

**Comment by planetf1** [comment]
Update
 - further database issues found in #7566 but now resolved & merged
  - waiting for #7534 
  - various gradle issues found & resolved
  
  Publishing to Sonatype nexus (oss.sonatype.org) :
  
   - Our bom is going into a seperate staging repo to the other components (threading?) - may not be a problem
   - Every artifact is reporting it is not signed with `Missing Signature: '/org/odpi/egeria/database-integrator-api/4.0/database-integrator-api-4.0-javadoc.jar.asc' does not exist for 'database-integrator-api-4.0-javadoc.jar'.`
    - BOM is also failing with `Invalid POM: /org/odpi/egeria/egeria/4.0/egeria-4.0.pom: Project name missing`
    - BOM is also failing with `Requires one-of SHA-1: /org/odpi/egeria/egeria/4.0/egeria-4.0.pom.sha1, MD5: /org/odpi/egeria/egeria/4.0/egeria-4.0.pom.md5, SHA-256: /org/odpi/egeria/egeria/4.0/egeria-4.0.pom.sha256, SHA-512: /org/odpi/egeria/egeria/4.0/egeria-4.0.pom.sha512`

**Comment by planetf1** [comment]
Release pipeline now tested & problems fixed. Artifacts upload to staging repository on oss.sonatype.org and validate clean.

Awaiting final fix, and testing to do.

**Comment by planetf1** [comment]
Update of outstanding issues:

The base is now looking much better, and the pipelines are working well.
Unfortunately, interacting with it is harder ... ;-)

* https://github.com/odpi/egeria-react-ui/issues/new ( @davidradl) - errors on viewing assets in react UI
* https://github.com/odpi/egeria-ui (@bogdan-sava @lpalashevski ) - this may be a chassis error
* https://github.com/odpi/egeria-charts (@dwolfson @planetf1 ) - not a bug, but a usability challenge

**Comment by planetf1** [comment]
Business UI now deploys correctly, and simple testing is successful (asset search, view lineage, login) albeit with a number of issues found in the UI. They will be addressed through the issue, and potentially release notes

With all the required fixes in, I am now going to progress to creating the final release for egeria 4.0.
I’ve updated release notes, and will add a few more entries including around the business UI where there are some caveats

The charts will follow asap (just a final release of the egeria-react-ui 
 to increment the dependency for. Purely a version bump, testing is good)

**Comment by planetf1** [comment]
release 4 is now out
