### ISSUE TITLE
[RELEASE] Release 4.1

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7649]
### Work Plan

Create release x.y :
Prior to the release work
- [ ] slack post advising of upcoming release & linking to issue
- [ ] advance warning in developer/community call
- [ ] final agreement to start branch in team call & identification of outstanding issues
- [ ] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [ ] Create branch
- [ ] Reassign any issues not being worked on to the next release
- [ ] Update version for main (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [ ] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [ ] Ensure any remaining fixes are merged into branch (and vice-versa to main)

Pre-release security check
- [ ] Execute manual [sonatype lift scan](https://lift.sonatype.com) on release branch from and communicate findings (needs more formal process in future)

Generate a release image for testing
- [ ] Start [Release](https://github.com/odpi/egeria/actions/workflows/release.yml) pipeline manually to generate container image

Updating the Helm Charts (egeria-charts repo)
- [ ] checker correct container images are on [docker.io](https://hub.docker.com/u/odpi) & [quay.io](https://quay.io/organization/odpi) (these are built by the 'merge' build of a release)
- [ ] update image versions for helm charts [egeria-charts](https://github.com/odpi/egeria-charts/) repo (using -prerelease for chart version)
  - check/update the strimzi chart versions
  - check/update the kafka version used for the strimzi CR in each chart
  - check/update the current jupyter lab version & generate a new docker container in egeria-jupyter
  - update the jupyter lab version in the charts

Final tests
- [ ] Check [swagger doc](https://egeria-project.org/education/tutorials/swagger-tutorial/overview/?h=swagger) renders (no regressions)
- [ ] Verify odpi-egeria-lab chart (pods active/ready)
- [ ] Verify egeria-base chart (pods active/ready)
- [ ] Check notebooks (config, start, data catalog at a minimum)
- [ ] Check polymer UI (only possible to check it runs and run UI lab)
- [ ] Check React UI (rex, tex, glossary author). Some of the steps descibed [here](https://egeria-project.org/education/egeria-dojo/running-egeria/user-interfaces/ecosystem-ui/ecosystem-ui-start/)
- [ ] [CTS - graph](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)
- [ ] [CTS - inmemory](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)

Final Docs
- [ ] Update release notes in egeria-docs

Final build and publish
- [ ] Check if the Release pipeline rlease artifacts are shown in staging repo in [OSS Repository Manager](https://oss.sonatype.org/#welcome)
- [ ] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [ ] Create final github releases for egeria (add link to egeria docs)
- [ ] Close repo on oss.sonatype.org (once updated) for egeria, release
- [ ] Check 'release' repo on oss.sonatype.org has artifacts
- [ ] Update final versions of egeria-charts to release ie x.y
- [ ] Publish that release is now shipped via slack #egeria-announce
- [ ] Post on egeria-annouce [mailing list](egeria-announce@lists.lfaidata.foundation)
- [ ] Additional posts to social media
- [ ] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed (Egeria Dev Projects etc.)

Get Ready for next release
- [ ] Open Release Issue for next release

**Comment by planetf1** [comment]
Currently planned for June (ie branch nearing the end of May).
cc: @mandy-chessell @lpalashevski Suggest we discuss schedule in our TSC call Wed 3 May.

**Comment by lpalashevski** [comment]
Release is complete closing the issue. 
Next release https://github.com/odpi/egeria/issues/7698
