### ISSUE TITLE
[RELEASE] Release 4.2

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#7698]
### Work Plan

Create release x.y :
Prior to the release work
- [x] slack post advising of upcoming release & linking to issue
- [ ] advance warning in developer/community call
- [x] final agreement to start branch in team call & identification of outstanding issues
- [ ] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch
- [ ] Reassign any issues not being worked on to the next release
- [x] Update version for main (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [ ] Ensure any remaining fixes are merged into branch (and vice-versa to main)

Pre-release security check
- [ ] Execute manual [sonatype lift scan](https://lift.sonatype.com) on release branch from and communicate findings (needs more formal process in future)

Generate a release image for testing
- [x] Start [Release](https://github.com/odpi/egeria/actions/workflows/release.yml) pipeline manually to generate container image

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on [docker.io](https://hub.docker.com/u/odpi) & [quay.io](https://quay.io/organization/odpi) (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts [egeria-charts](https://github.com/odpi/egeria-charts/) repo (using -prerelease for chart version)
  - check/update the strimzi chart versions
  - check/update the kafka version used for the strimzi CR in each chart
  - check/update the current jupyter lab version & generate a new docker container in egeria-jupyter
  - update the jupyter lab version in the charts

Final tests
- [x] Check [swagger doc](https://egeria-project.org/education/tutorials/swagger-tutorial/overview/?h=swagger) renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check polymer UI (only possible to check it runs and run UI lab)
- [x] Check React UI (rex, tex, glossary author). Some of the steps descibed [here](https://egeria-project.org/education/egeria-dojo/running-egeria/user-interfaces/ecosystem-ui/ecosystem-ui-start/)
- [x] [CTS - graph](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)
- [x] [CTS - inmemory](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)

Final Docs
- [x] Update release notes in egeria-docs

Final build and publish
- [x] Check if the Release pipeline rlease artifacts are shown in staging repo in [OSS Repository Manager](https://oss.sonatype.org/#welcome)
- [x] 'close' staging repo & Validate artifacts ok (number, structure, validations) on oss.sonatype.org
- [x] Create final github releases for egeria (add link to egeria docs)
- [x] Close repo on oss.sonatype.org (once updated) for egeria, release
- [ ] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [x] Post on egeria-annouce [mailing list](egeria-announce@lists.lfaidata.foundation)
- [ ] Additional posts to social media
- [ ] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed (Egeria Dev Projects etc.)

Get Ready for next release
- [ ] Open Release Issue for next release

**Comment by lpalashevski** [comment]
CTS test are failing for graph repo and this is delaying the branching for a while. Investigation ongoing.

**Comment by lpalashevski** [comment]
Release 4.2 has been shipped, 1closing this issue.
Next release #7794

**Comment by mandy-chessell** [comment]
Thank you @lpalashevski
