### ISSUE TITLE
[RELEASE] Release 4.3

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#7794]
### Work Plan

Create release x.y :
Prior to the release work
- [x] Slack post advising of upcoming release & linking to issue
- [x] Advance warning in developer/community call
- [x] Final agreement to start branch in team call & identification of outstanding issues
- [ ] Agree required updates/versions for additional repos including egeria-ui, egeria-reactui, connectors etc

Branching & Correcting versions
- [x] Create branch (egeria-release-x.y)
- [x] Reassign any issues not being worked on to the next release
- [x] Update version for main (ie x.y-SNAPSHOT > x.y+1-SNAPSHOT)
- [x] Update version for release branch (ie x.y-SNAPSHOT -> x.y)

Final updates to the release
- [x] Ensure any remaining fixes are merged into branch (and vice-versa to main)

Pre-release security check
- [ ] Check security scans (ie owasp dependency check)

Generate a release image for testing
- [x] Start [Release](https://github.com/odpi/egeria/actions/workflows/release.yml) pipeline manually to generate container image and stage artifacts on maven central

Updating the Helm Charts (egeria-charts repo)
- [x] checker correct container images are on [docker.io](https://hub.docker.com/u/odpi) & [quay.io](https://quay.io/organization/odpi) (these are built by the 'merge' build of a release)
- [x] update image versions for helm charts [egeria-charts](https://github.com/odpi/egeria-charts/) repo (using -prerelease for chart version)
  - check/update the [strimzi chart versions](https://github.com/strimzi/strimzi-kafka-operator/releases)
  - check/update supported kafka version used for the strimzi CR in each chart
  - check/update the current [jupyter lab version](https://hub.docker.com/r/jupyter/minimal-notebook/tags) & generate a new docker image in egeria-jupyter
  - update the jupyter lab image version in the charts

Final tests
- [x] Check [swagger doc](https://egeria-project.org/education/tutorials/swagger-tutorial/overview/?h=swagger) renders (no regressions)
- [x] Verify odpi-egeria-lab chart (pods active/ready)
- [x] Verify egeria-base chart (pods active/ready)
- [x] Check notebooks (config, start, data catalog at a minimum)
- [x] Check Egeria UI (only possible to check it runs and run UI lab)
- [ ] Check React UI (rex, tex, glossary author). Some of the steps descibed [here](https://egeria-project.org/education/egeria-dojo/running-egeria/user-interfaces/ecosystem-ui/ecosystem-ui-start/)
- [ ] Check and validate [CTS results](https://egeria-project.org/guides/operations/kubernetes/charts/cts/)
  - CTS using in-memory
  - CTS using graph
  - CTS using xtdb

Final Docs
- [x] Update release notes in [egeria-docs](https://github.com/odpi/egeria-docs/tree/main/site/docs/release-notes)

Final build and publish
- [x] Check if the Release pipeline rlease artifacts are shown in staging repo in [OSS Repository Manager](https://oss.sonatype.org/#welcome)
- [x] Close staging repo & validate artifacts ok (number, structure, validations) on oss.sonatype.org 
- [x] Check 'release' repo on oss.sonatype.org has artifacts
- [x] Release the repo (takes time for the operation to complete and for the arifacts to be visible in maven central repository)
- [x] Create final [github release](https://github.com/odpi/egeria/releases) (add link to egeria docs)
- [x] Update final versions of egeria-charts to release ie x.y
- [x] Publish that release is now shipped via slack #egeria-announce
- [ ] Post on egeria-annouce [mailing list](egeria-announce@lists.lfaidata.foundation)
- [ ] Additional posts to social media
- [ ] Communicate to other repo owners ie for connectors so that they can be rebuilt/shipped as needed (Egeria Dev Projects etc.)

Get Ready for next release
- [ ] Open Release Issue for next release

**Comment by lpalashevski** [comment]
Release ready, closing the issue
New release issue https://github.com/odpi/egeria/issues/7864
